// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQsIcCctfS6neYrJvqYQuvC5ffktXfIFg',
    appId: '1:434985768670:web:72c43f2f3717b1e6fc944f',
    messagingSenderId: '434985768670',
    projectId: 'fir-project2-42ab4',
    authDomain: 'fir-project2-42ab4.firebaseapp.com',
    storageBucket: 'fir-project2-42ab4.firebasestorage.app',
    measurementId: 'G-HH48NNTK4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC33NOJ8oNGHr4zmqw_OUW1k_zTV3mHyZE',
    appId: '1:434985768670:android:9acee2f7ccb7fd50fc944f',
    messagingSenderId: '434985768670',
    projectId: 'fir-project2-42ab4',
    storageBucket: 'fir-project2-42ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHzDf5SJjAa_KT8h6w5i5KVPeAviV_Yxc',
    appId: '1:434985768670:ios:0f472ea3e0699af5fc944f',
    messagingSenderId: '434985768670',
    projectId: 'fir-project2-42ab4',
    storageBucket: 'fir-project2-42ab4.firebasestorage.app',
    iosBundleId: 'com.example.finalConstruction',
  );
}
